# AI and ML for Coders Ch 4

This will be a short one demonstrating Tensorflow datasets. 

Good reference for knowing it's capabilities.

In [1]:
!pip install tensorflow-datasets

Pass the name of the dataset ro the argumane of `load()`

In [2]:
import tensorflow as tf 
import tensorflow_datasets as tfds
mnist_data = tfds.load("fashion_mnist")
for item in mnist_data:
  print(item)

train
test


These are dictionary key strings: train and test

Let's now load the training data only

In [3]:
mnist_train = tfds.load(name="fashion_mnist", split="train")
assert isinstance(mnist_train, tf.data.Dataset)
print(type(mnist_train))

<class 'tensorflow.python.data.ops.dataset_ops.PrefetchDataset'>


In [4]:
for item in mnist_train.take(1):
  print(type(item))
  print(item.keys())
  print(item['image'])
  print(item['label'])

<class 'dict'>
dict_keys(['image', 'label'])
tf.Tensor(
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 18]
  [ 77]
  [227]
  [227]
  [208]
  [210]
  [225]
  [216]
  [ 85]
  [ 32]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 61]
  [100]
  [ 97]
  [ 80]
  [ 57]
  [117]
  [227]
  [238]
  [115]
  [ 49]
  [ 78]
  [106]
  [108]
  [ 71]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 81]
  [105]
  [ 80]
  [ 69]
  [ 72]
  [ 64]
  [ 44]
  [ 21]
  [ 13]
  [ 44]
  [ 69]
  [ 75]
  [ 75]
  [ 80]
  [114]
  [ 80]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 26]
  [ 92]
  [ 69]
  [ 68]
  [ 75]
  [ 75]
  [ 71]
  [ 74]
  [ 83]
  [ 75]
  [ 77]
  [ 78]
  [ 74]
  [ 74]
  [ 83]
  [ 77]
  [108]
  [ 34]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]


You can also grab info about the data

In [5]:
mnist_test, info = tfds.load("fashion_mnist", with_info="true")
print(info)

tfds.core.DatasetInfo(
    name='fashion_mnist',
    full_name='fashion_mnist/3.0.1',
    description="""
    Fashion-MNIST is a dataset of Zalando's article images consisting of a training set of 60,000 examples and a test set of 10,000 examples. Each example is a 28x28 grayscale image, associated with a label from 10 classes.
    """,
    homepage='https://github.com/zalandoresearch/fashion-mnist',
    data_path='/Users/adrianmoses/tensorflow_datasets/fashion_mnist/3.0.1',
    download_size=29.45 MiB,
    dataset_size=36.42 MiB,
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=tf.uint8),
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=10),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'test': <SplitInfo num_examples=10000, num_shards=1>,
        'train': <SplitInfo num_examples=60000, num_shards=1>,
    },
    citation="""@article{DBLP:journals/corr/abs-1708-07747,
      author    = {Han 

## Using TFDS with Keras Models

Here's how to load in trainging and test data for feeding into keras models

Note: `as_supervised` ensures we get tuples of (X, y)

In [6]:
(training_images, training_labels), (test_images, test_labels) = tfds.as_numpy(tfds.load('fashion_mnist',
  split=['train','test'],
  batch_size=-1,
  as_supervised=True))

Instructions for updating:
Use `tf.data.Dataset.get_single_element()`.


Instructions for updating:
Use `tf.data.Dataset.get_single_element()`.


In [7]:
# ensure the keras model input_shape is (28, 28, 1)
training_images.shape

(60000, 28, 28, 1)

Batch datasets with `.batch()` call

In [8]:
data = tfds.load('horses_or_humans', split='train', as_supervised=True)

train_batches = data.shuffle(100).batch(10)

In [10]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Conv2D(16, (3,3), activation='relu', input_shape=(300, 300, 3)),
  tf.keras.layers.MaxPooling2D(2, 2),
  tf.keras.layers.Conv2D(32, (3, 3), activation='relu'),
  tf.keras.layers.MaxPooling2D(2, 2),
  tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
  tf.keras.layers.MaxPooling2D(2, 2),
  tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
  tf.keras.layers.MaxPooling2D(2, 2),
  tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
  tf.keras.layers.MaxPooling2D(2, 2),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(512, activation='relu'),
  tf.keras.layers.Dense(1, activation='sigmoid'),
])

model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])

history = model.fit(train_batches, epochs=1)

103/103 [==============================] - 24s 225ms/step - loss: 3.0123 - accuracy: 0.8471


Load cells by version using the semver version system.

In [12]:
data, info = tfds.load("cnn_dailymail:3.1.0", with_info=True)

Dl Completed...: 0 url [00:00, ? url/s]
Dl Completed...: 100%|██████████| 5/5 [00:13<00:00,  3.31s/ url]

Dl Completed...: 100%|██████████| 5/5 [01:07<00:00,  3.31s/ url]

Extraction completed...: 100%|██████████| 2/2 [02:12<00:00, 66.35s/ file]
Dl Size...: 557 MiB [02:12,  4.20 MiB/s]
Dl Completed...: 100%|██████████| 5/5 [02:12<00:00, 26.54s/ url]


Dataset cnn_dailymail downloaded and prepared to /Users/adrianmoses/tensorflow_datasets/cnn_dailymail/3.1.0. Subsequent calls will reuse this data.


Mapping functions iwth data augmentation

In [13]:
data = tfds.load('horses_or_humans', split='train', as_supervised=True)

In [14]:
def augment_images(image, label):
  image = tf.cast(image, tf.float32)
  image = (image/255)
  image = tf.image.random_flip_left_right(image)
  return image, label

In [15]:
train = data.map(augment_images)

Use Tensorflow Addons to use more augmentation features

In [16]:
!pip install tensorflow-addons

     |████████████████████████████████| 575 kB 5.1 MB/s 


In [17]:
import tensorflow_addons as tfa

def augment_images(image, label):
  image = tf.cast(image, tf.float32)
  image = (image/255)
  image = tf.image.random_flip_left_right(image)
  image = tfa.image.rotate(image, 40, interpolation='NEAREST') # rotate and fill with nearest neighboars
  return image, label

## Using Custom Splits

Apply custom splits with the `split=` keyword arg

In [18]:
def load_cats_vs_dogs(split_string):
  return tfds.load('cats_vs_dogs', split=split_string, as_supervised=True)


train_data = load_cats_vs_dogs('train[:80%]')

validation_data = load_cats_vs_dogs('train[80%:90%]')

test_data = load_cats_vs_dogs('train[-10%:]')

Dl Completed...:   0%|          | 0/1 [00:00<?, ? url/s]

Generating splits...:   0%|          | 0/1 [00:00<?, ? splits/s]WARNING:absl:1738 images were corrupted and were skipped


Dataset cats_vs_dogs downloaded and prepared to /Users/adrianmoses/tensorflow_datasets/cats_vs_dogs/4.0.0. Subsequent calls will reuse this data.



Files can be loaded in parallel

In [19]:
file_pattern = '/Users/adrianmoses/tensorflow_datasets/cats_vs_dogs/4.0.0/cats_vs_dogs-train.tfrecord*'

files = tf.data.Dataset.list_files(file_pattern)

train_dataset = files.interleave(
  tf.data.TFRecordDataset, 
  cycle_length=4, # records at a time (concurrently)
  num_parallel_calls=tf.data.experimental.AUTOTUNE # dynamically set based on available CPUs, use multiprocessing if not
)